### ISSUE TITLE
Mobile nav bar zoomable

### ISSUE THREAD

**Issue by JoelBalmer** [JoelBalmer/joelbalmermusic#2]
Using this makes the nav bar lose its stickiness:

``` css
.navbar {
    position: absolute;
}
```

Find a solution or don't fix
